### ISSUE TITLE
Small error in the path name?

### ISSUE THREAD

**Issue by GindaChen** [LinuxPerfStudy/LEBench#3]
I think the intention of the following two lines is to concat the two paths and make the test directory like `<home>/<sock>`

https://github.com/LinuxPerfStudy/LEBench/blob/c0663d16e50ba96fd9718b506533be7644a6f29f/TEST_DIR/OS_Eval.c#L905-L906

Should this be instead:
```C
strncpy(server_addr.sun_path, home, sizeof(server_addr.sun_path) - 1); 	
strncat(server_addr.sun_path, sock, sizeof(server_addr.sun_path) - 1);
```

since we want to concat the paths, instead of overwriting the path?

Thanks! Love the paper and really appreciate the enourmous amount of work you guys needed to do for that!

**Comment by LinuxPerfStudy** [comment]
Thanks! that's a good catch. Will push a patch soon.
